---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

## Education

- Master of Public Health (Epidemiology), Columbia University 

- BS / MS in Nursing, St. Luke's International University, Tokyo, Japan


## Publication 
- Kawanami, M., Furuya, A., Whalen, A. M., Callander, D., Radix, A., Merriman, J., Trinh-Shevrin, C., Sahnah Lim, S., & Duncan, D. T. (in submission). Cross-Sectional and Longitudinal Associations Between Food Insecurity and Psychological Distress Among Transgender Women of Color: A TURNNT Cohort Study. Transgender Health.
- Yang, Y., Whalen, A. M., Barreto, G. A., Kawanami, M., Regan, S. D., Aldstadt, J., Chaix, B., & Duncan, D. T. (in submission). Global positioning system–derived individual mobility variables for spatial epidemiologic studies. Health & Place.
- Kawanami, M. & Okubo, N (2021). A Review of the Literature on the Changes in Behavior and Self-awareness Among Preschool Children After Learning About Their Body. Bulletin of St. Luke’s International University, 7, 57-65. https://doi.org/10.34414/00016399

## Presentation
- Kawanami, M., & Surachman, F. (2026, April). Meritorious Abstract Award Winner: F133-Telework, parenting and Mental health: Evidence from the 2024 U.S. Household Pulse Survey. Poster presented at the 47th Annual Meeting & Scientific Sessions: Society of Behavioral Medicine, Chicago, IL. https://doi.org/10.1093/abm/kaag012
- Kawanami, M. (2025, November). Playful parenting for caregiver well-being: Understanding the evidence and implications for program design. Poster presented at the Mailman School of Public Health, Columbia University, New York, NY.
- Kawanami, M., Ota, E., Kobayashi, M., & Ma, P. (2022, November). Nurse-led lifestyle interventions for metabolic syndrome, overweight, or obesity: A systematic review. Poster presented at the American Public Health Association Annual Meeting, Boston, MA.


Go back to the [homepage](index.html)
