---
title: "Temporal and Geographic Patterns of Critical Violations in Japanese Restaurants (NYC)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```


```{r include=FALSE}
## Checked variable names
data(rest_inspec)
names(rest_inspec)
```


```{r include=FALSE}
## Japanese restaurants, filter
jp_critical = rest_inspec |>
  mutate(
    inspection_date = ymd(inspection_date),
    score = suppressWarnings(as.numeric(score)),
    month = floor_date(inspection_date, "month"),
    season = case_when(
      month(inspection_date) %in% c(12, 1, 2) ~ "Winter",
      month(inspection_date) %in% c(3, 4, 5) ~ "Spring",
      month(inspection_date) %in% c(6, 7, 8) ~ "Summer",
      month(inspection_date) %in% c(9, 10, 11) ~ "Fall",
      TRUE ~ NA_character_
    )
  ) |>
  filter(
    cuisine_description == "Japanese",
    !is.na(inspection_date),
    !is.na(score),
    !is.na(boro),
    boro != "Missing",
    !is.na(zipcode),
    !is.na(season),
    !is.na(critical_flag),
    critical_flag == "Y"   
  )
```


```{r include=FALSE}
# 1) per month x borough: number of critical cases
jp_monthly = jp_critical |>
  count(month, boro, name = "n_critical")

# 2) season x borough: number of critical cases
jp_seasonal = jp_critical |>
  count(season, boro, name = "n_critical")

```

Trends Over Time {.tabset}
-----------------------------------------------------------------------
### Chart A: Monthly Counts
```{r}
line_month = plot_ly(
data = jp_monthly,
x = ~month,
y = ~n_critical,
color = ~boro,
type = "scatter",
mode = "lines+markers",
hoverinfo = "text",
text = ~paste0(
"Borough: ", boro,
"<br>Month: ", month,
"<br>Critical violations: ", n_critical
)
) |>
layout(
xaxis = list(title = "Inspection month"),
yaxis = list(title = "Number of critical violations"),
legend = list(title = list(text = "Borough"))
)

line_month

```


### Chart B: Seasonal Trends

```{r}
bar_season = plot_ly(
data = jp_seasonal,
x = ~season,
y = ~n_critical,
color = ~boro,
type = "bar",
hoverinfo = "text",
text = ~paste0(
"Season: ", season,
"<br>Borough: ", boro,
"<br>Critical violations: ", n_critical
)
) |>
layout(
barmode = "group",
xaxis = list(title = "Season"),
yaxis = list(title = "Number of critical violations"),
legend = list(title = list(text = "Borough"))
)

bar_season
```

Location Patterns {.tabset}
-----------------------------------------------------------------------
### Chart C: Score Distribution by Borough

```{r}
box_boro = jp_critical |>
  plot_ly(
    x = ~boro,
    y = ~score,
    color = ~boro,
    type = "box",
    hoverinfo = "text",
    text = ~paste0(
      "Borough: ", boro,
      "<br>Score: ", score,
      "<br>Date: ", inspection_date
    )
  ) |>
  layout(
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Inspection score (higher = worse)"),
    showlegend = FALSE,
    title = "Score distribution by borough (critical violations only)"
  )

box_boro
```


### Chart D: Location of Japanese Restaurants in NYC

```{r}
scatter_geo =
  jp_critical |>
  ggplot(aes(x = longitude, y = latitude, color = score,  text = paste(
      "Name:", dba,
      "<br>Borough:", boro,
      "<br>Score:", score
    ))) +
  geom_point(alpha = 0.5, size = 1.5) +
  scale_color_viridis_c(option = "plasma", direction = -1) +
  labs(
    x = "Longitude",
    y = "Latitude",
    color = "Score",
    title = "Location of Japanese restaurants with critical violations in NYC"
  ) +
  theme_minimal()

ggplotly(scatter_geo, tooltip = "text")
```

